### ISSUE TITLE
Write down rules for patching training frameworks

### ISSUE THREAD

**Issue by TheKanter** [mlcommons/policies#62]
We have rules for submitting training results using patched frameworks. Can we write them down clearly?

**Comment by petermattson** [comment]
I believe this is handled by the existing availability rules.
Patch is a sw component. If it's public, versioned, and supported it's
Available. If it's not, it's not.

**Comment by christ1ne** [comment]
shall we close this? @TheKanter

**Comment by TheKanter** [comment]
Yes, let's close.
