### ISSUE TITLE
For preview submission - requesting exemption to not include processor  model name and core count

### ISSUE THREAD

**Issue by rnchukka** [mlcommons/policies#97]
For Next Inference submission, Intel cannot disclose host_processor_model_name and host_processor_core_count in [system description](https://github.com/mlcommons/policies/blob/master/submission_rules.adoc#57-system_desc_idjson-metadata) json mentioned in submission rules for a product that is not launched yet.  Intel is requesting for exemption to not to include **host_processor_model_name** and **host_processor_core_count** for **preview** submission only.

**Comment by rnaidu02** [comment]
Ramesh will create a PR with proposal to cover this request.

**Comment by georgelyuan** [comment]
Ramesh, can Intel retroactively amend the system JSON once the product has launched?
